

# GO
[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }


# PYTHON
[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
[language-server.ruff]
command = "ruff-lsp"
[language-server.ruff.config.settings]
args = ["--ignore", "E501"]
[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]


# SQL
[[language]]
name = "sql"
language-servers = [ "sql-language-server" ]
[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]


# TAILWIND
[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]
[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]
[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]
[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]
[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls" ]


# TERRAFORM
[[language]]
name = "hcl"
language-servers = [ "terraform-ls" ]
language-id = "terraform"
[[language]]
name = "tfvars"
language-servers = [ "terraform-ls" ]
language-id = "terraform-vars"
[language-server.terraform-ls]
command = "terraform-ls"
args = ["serve"]

# YAML
[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
language-servers = [ "yaml-language-server" ]
auto-format = true
formatter = { command = "prettier", args = [ "--parser", "yaml" ] } 
[language-server.yaml-language-server.config.yaml]
completion = true
validation = true
hover = true
[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/master/service-schema.json" = "CI_*/pipeline.yaml"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"
"/home/maha/src/lab3/terraform-azurerm-lab3-tfe/files/tfe-config-test.json" = "tfe-config.yaml"
format = { enable = true }

