[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
language-servers = [ "yaml-language-server" ]
auto-format = true
formatter = { command = "prettier", args = [ "--parser", "yaml" ] }


[language-server.yaml-language-server.config.yaml]
completion = true
validation = true
hover = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/master/service-schema.json" = "CI_*/pipeline.yaml"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"
# "/home/maha/src/lab3/terraform-azurerm-lab3-tfe/files/tfe-config.json" = "tfe-config.yaml"
"/home/maha/src/lab3/terraform-azurerm-lab3-tfe/files/tfe-config-test.json" = "tfe-config.yaml"
format = { enable = true }


# [[language]] 
# name = "typst" 
# formatter = { command = "typstfmt", args = ["--output", "-"] } 
# auto-format = true


# [language-server.ruff-lsp]
# command = "ruff-lsp"

# [[language]]
# name = "python"
# language-servers = [ "ruff-lsp" ]


[[language]]
name = "hcl"
language-servers = [ "terraform-ls" ]
language-id = "terraform"

[[language]]
name = "tfvars"
language-servers = [ "terraform-ls" ]
language-id = "terraform-vars"

[language-server.terraform-ls]
command = "terraform-ls"
args = ["serve"]
